version: '3.8'

services:
  worker:
    image: dockerregistry.etdofresh.com/collaborative-session-worker:latest
    environment:
      PORT: 8080
      WORKSPACE_DIR: /workspace
      COOLDOWN_MS: 300000
      # MinIO disabled for now - running in local-only mode
      # MINIO_ENDPOINT: minio
      # MINIO_PORT: 9000
      # MINIO_BUCKET: sessions
      # MINIO_ACCESS_KEY: minioadmin
      # MINIO_SECRET_KEY: minioadmin
    # Port mapping removed - access via reverse proxy only
    # ports:
    #   - "8080:8080"
    networks:
      - worker-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  worker-network:
    driver: overlay
